const styles = {
  custom_container: "w-11/12 hidden sm:block",
  heading: 'text-[27px] text-center xl:text-start font-[600] font-Roboto pb-[20px]',
  section: 'w-11/12 mx-auto',
  productTitle: 'text-[25px] font-[600] font-Roboto text-[#333]',
  productDiscountPrice: "font-bold text-[18px] text-[#333] font-Roboto",
  price: "font-[500] text-[16px] text-[#d55b45] pl-3 mt-[-4px] line-through",
  shop_name: "pt-3 text-[15px] text-blue-400 pb-3",
  active_indicator: "absolute bottom-[-27%] left-0 h-[3px] w-full bg-[crimson]",
  category_buttion: 'relative border-[#3957db] bg-white h-[40px] w-[300px] hidden text 1000px:block',
  cart_button: "px-[20px] h-[38px] rounded-[20px] bg-[#f63b60] flex items-center justify-center cursor-pointer",
  cart_button_text: "text-[#fff] text-[16px] font-[600]",
  // input: "w-full border p-1 rounded-[5px]",
  activeStatus: "w-[10px] h-[10px] rounded-full absolute top-0 right-1 bg-[#40d132]",
  noramlFlex: "flex items-center",
  // auth

  auth_container: "min-h-screen flex flex-col justify-center p-5",
  auth_title: "mx-auto w-full max-w-xl text-center text-3xl font-bold mb-3 space-y-3",
  auth_form: "mx-auto w-full max-w-xl rounded-md border-[1px] border-black p-5 space-y-3",
  auth_visible: "absolute right-3 top-3",
  n_center_lr_align: "flex items-center justify-between space-x-1 p-1",
  n_center_align:"flex justify-center items-center p-1 space-x-1",
  n_hover: "hover:opacity-30 cursor-pointer",
  n_input_label: "text-sm mb-3",
  n_btn: "w-full h-[40px] flex justify-center items-center p-3 rounded-xl border-[1px] border-black hover:opacity-30 cursor-pointer",
  n_input: "appearance-none block w-full p-3 shadow rounded-md focus:outline-none focus:ring-1 focus:ring-black",
  right_tab_bg: "fixed top-0 left-0 w-full bg-black/5 h-screen z-10",
  right_tab_header: "flex w-full justify-between p-3 text-xl",
  right_tab_container: "space-y-1 p-1 fixed xl:top-3 xl:right-3 min-h-full w-[99%] xl:w-[25%] bg-white flex flex-col rounded-md",
  right_tab_item_container: "border-y p-1 w-full flex justify-between space-x-1",
  right_tab_item_count_container: "flex flex-col items-center justify-center text-md",
  right_tab_item_count_btn: "w-[25px] h-[25px] flex items-center cursor-pointer hover:opacity-30",
  right_tab_item_img: "w-[75px] h-[75px]",
  right_tab_item_content: "flex flex-col space-y-1 overflow-x-auto text-sm xl:text-base",
  n_section: "w-11/12 mx-auto mb-3",
  n_section_title: "mb-3 border-[1px] border-black rounded-md text-xl font-bold text-center",
  n_flex_col:"flex flex-col",
  swiper: "mb-3 border-[1px] border-black rounded-md cursor-pointer",
  swiper_item: "border-x-[1px] border-b-[1px] border-black mb-10 hover:opacity-30 text-center",
  slider: "w-11/12 mx-auto h-[400px] mb-3 relative group rounded-md border-[1px] border-black",
  slider_img: "w-full h-full bg-center bg-cover rounded-md",
  slider_btn: "hidden group-hover:block absolute top-[50%] -translate-x-0 translate-y-[-50%] text-3xl rounded-full p-3 border-[1px] border-black bg-white cursor-pointer",
  slider_idx_view: "absolute bottom-5 right-0 left-0 flex items-center justify-center gap-2",
  slider_idx_dot:"transition-all w-3 h-3 bg-black rounded-full",
  category_dropdown_container:"mt-[13px] mr-1 rounded-md flex flex-row bg-white z-30 absolute border-b-[1px] border-x-[1px] border-black",
  category_dropdown_item:"m-3 p-3  rounded-md cursor-pointer select-none text-sm xl:text-base border-[1px] border-black ",
  move_to_top_btn: "bg-black text-white fixed z-99 hover:opacity-30 w-[40px] h-[40px] cursor-pointer items-center justify-center rounded-full p-3 border-[1px] border-black  bottom-3 right-3 ",
  footer_section:"hidden md:block w-11/12 mx-auto border-[1px] border-black rounded-md text-[20px] text-center bg-white mb-10",
  footer_sponsor:"mb-5 cursor-pointer flex flex-row w-full justify-center space-x-3",
  footer_input:"p-3 w-[30%] border-[1px] appearance-none block  rounded-md h-[30px] border-black focus:outline-none",
  footer_btn:"px-3 hover:opacity-50 rounded-md border-black border-[1px] h-[30px] text-[15px] items-center justify-center",
  footer_container:"flex justify-center items-center mb-3 space-x-3 text-sm",
  top_header_section:"h-[50px] my-[20px] flex xl:flex flex-col xl:flex-row items-center justify-between",
  top_header_logo: "flex xl:block text-sm xl:text-3xl font-extrabold mb-1",
  top_header_search_input:"flex w-full xl:w-full h-[40px] p-1 border-[1px] border-black focus:outline-none rounded-md",
  top_header_search_container:"w-full xl:w-[50%] relative"
};

export const customRenderDot = (index: number, className: string) => { return `<span class="${className}" style="background-color: black;"></span>`; };

export default styles;
